services:
  restate:
    image: docker.io/restatedev/restate:latest
    ports:
      - "8080:8080"  # HTTP API
      - "9070:9070"  # Admin API
      - "9071:9071"  # Metrics
    volumes:
      - ./.restate-data:/restate-data
    environment:
      - RUST_LOG=info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9070/health"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # FastAPI application
    depends_on:
      restate:
        condition: service_healthy
    environment:
      - RESTATE_ENDPOINT=http://restate:8080
    volumes:
      - ./src:/app/src
