services:
  restate:
    image: docker.io/restatedev/restate:latest
    ports:
      - "8080:8080"  # HTTP API
      - "9070:9070"  # Admin API
      - "9071:9071"  # Metrics
    volumes:
      - ./.restate-data:/restate-data
    environment:
      - RUST_LOG=info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9070/health"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      restate:
        condition: service_healthy
    environment:
      - RESTATE_ENDPOINT=http://restate:8080
    ports:
      - "8008:8008"
    volumes:
      - ./src:/app/src

  link:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: "python"
    command: ["-m", "src.edge_link.main"]
    depends_on:
      nats:
        condition: service_started
    volumes:
      - ./src:/app/src

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: "hypercorn"
    command: ["--bind", "0.0.0.0:9080", "--reload", "src.worker.main:app"]
    depends_on:
      restate:
        condition: service_healthy
    ports:
      - "9080:9080"
    volumes:
      - ./src:/app/src

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
